# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main, live ]
  pull_request:
    branches: [ main, live ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Make user app gradlew executable
      run: chmod +x ./user-auth/graphtutorial/gradlew
    - name: Build user app with Gradle
      uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
      with:
        build-root-directory: user-auth/graphtutorial
        arguments: build
    - name: Make app-only app gradlew executable
      run: chmod +x ./app-auth/graphapponlytutorial/gradlew
    - name: Build app-only app with Gradle
      uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
      with:
        build-root-directory: app-auth/graphapponlytutorial
        arguments: build
